//------------------------------------------------------------------------
// Copyright(c) 2024 Maximum Displacement.
//------------------------------------------------------------------------

#pragma once

#include "pluginterfaces/base/fplatform.h"

// Plain project version file generated by cmake 
#include "projectversion.h"

#define stringOriginalFilename	"Arpeggigator.vst3"
#if SMTG_PLATFORM_64
#define stringFileDescription	"Arpeggigator VST3 (64Bit)"
#else
#define stringFileDescription	"Arpeggigator VST3"
#endif
#define stringCompanyName		"Maximum Displacement\0"
#define stringLegalCopyright	"Copyright(c) 2024 Maximum Displacement."
#define stringLegalTrademarks	"VST is a trademark of Steinberg Media Technologies GmbH"
